### ISSUE TITLE
Consider using IndexMap

### ISSUE THREAD

**Issue by jesskfullwood** [glademiller/openapiv3#10]
It would be nice to preserve the order of object keys as provided by the user in the spec - the user can always sort the keys themselves if necessary. It should be a simple change, just swap out the instances of `BTreeMap` for [IndexMap](https://crates.io/crates/indexmap) - it has the same API. This is what e.g. [` serde_json` does.](https://github.com/serde-rs/json/blob/master/Cargo.toml#L47)

Happy to make a PR if you agree.

**Comment by glademiller** [comment]
I will have to mull this one over a bit. When I originally created the project I did say that it wasnt a goal to have a spec that is deserializedbe serialized again exactly the same as before and I know in a lot of places this has been followed such as creating a default when an empty value is parsed. Given that I'm not sure that there is too much value here since the raw spec will already be slightly different if reserialized. However, I am open to being convinced.

**Comment by jesskfullwood** [comment]
I agree in that having 1:1 serializability isn't a particularly useful goal. However, one major use for this library (what I am using it for) is to code-gen a server or client based on the spec. I think it is important to be able to present the API to the user in the order in which they specified it. 

For example I have a trait which contains a function corresponding to each endpoint, and it is surprising if the order of the functions is different from the order of paths in the spec. This is even more true when code-genning the `struct`s which correspond to the schema definitions, since the fields end up out-of-order.

I suppose the overall point it I don't think we can assume the ordering of the spec has no semantic meaning to the user.

**Comment by glademiller** [comment]
Good reasoning. Done.

**Comment by jesskfullwood** [comment]
Thanks, really appreciate it!
