### ISSUE TITLE
Add support for dereferencing `$ref`s

### ISSUE THREAD

**Issue by matusf** [glademiller/openapiv3#80]
Hi, would you please consider adding support for dereferencing `$ref`s? 

I created an [openapi-fuzzer](https://github.com/matusf/openapi-fuzzer) that uses OpenAPI Specification to generate structured inputs for fuzzing web service. As for now the `ReferenceOr<T>` objects often contain only strings with a location of given object. I'd would help me if I could resolve the `$ref`s and directly work with structured data.

**Comment by ahl** [comment]
I think that's beyond the intended scope of this crate... indeed resolving `$ref`s turns out to be quite involved, and may include opening other files or downloading documents from URLs. You can see an example of how to resolve references here:

https://github.com/oxidecomputer/progenitor/blob/main/progenitor-impl/src/util.rs#L13

**Comment by outlawpractice** [comment]
I disagree that that $ref handling is out of scope. It is a part of the spec, and most serious openapi files use refs for pure manageability (the one I am trying to parse is almost a MB without counting the many $refs!).  If the api was simple enough to not need $refs, it is likely simple enough to not need a generator.

I agree that downloading urls is not something we generally want to be doing, but I think handling $refs for files in the same directory structure as the original openapi file would be in scope.

Perhaps a simple include_str! macro call to load the local files would be simple enough?
